-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 20:15:08 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema perfulandia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema perfulandia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `perfulandia` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `perfulandia` ;

-- -----------------------------------------------------
-- Table `perfulandia`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`usuarios` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`username` ASC));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`sucursales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`sucursales` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `direccion` TEXT NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `encargado` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`vendedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`vendedores` (
  `id` BIGINT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `sucursal_id` BIGINT NOT NULL,
  `fechaIngreso` DATE NULL DEFAULT NULL,
  `activo` TINYINT NULL DEFAULT TRUE,
  PRIMARY KEY (`id`),
  INDEX (`usuario_id` ASC),
  INDEX (`sucursal_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`usuario_id`)
    REFERENCES `perfulandia`.`usuarios` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`sucursal_id`)
    REFERENCES `perfulandia`.`sucursales` (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`clientes` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `usuario_id` BIGINT NOT NULL,
  `nombre_completo` VARCHAR(100) NULL DEFAULT NULL,
  `rut` VARCHAR(12) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `direccion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`usuario_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`usuario_id`)
    REFERENCES `perfulandia`.`usuarios` (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`categorias` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`marcas` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`productos` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `stock` INT NULL DEFAULT NULL,
  `categoria_id` BIGINT NOT NULL,
  `marca_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`categoria_id` ASC),
  INDEX (`marca_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`categoria_id`)
    REFERENCES `perfulandia`.`categorias` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`marca_id`)
    REFERENCES `perfulandia`.`marcas` (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`ventas` (
  `id` BIGINT NULL AUTO_INCREMENT,
  `cliente_id` BIGINT NOT NULL,
  `vendedor_id` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `total` DECIMAL(10,2) NOT NULL,
  `descuento` DECIMAL(10,2) NULL DEFAULT NULL,
  `total_final` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX (`cliente_id` ASC),
  INDEX (`vendedor_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`cliente_id`)
    REFERENCES `perfulandia`.`clientes` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `perfulandia`.`vendedores` (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`detalle_venta` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `producto_id` BIGINT NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `precio_unitario` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`venta_id` ASC),
  INDEX (`producto_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`venta_id`)
    REFERENCES `perfulandia`.`ventas` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`producto_id`)
    REFERENCES `perfulandia`.`productos` (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`cupones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`cupones` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `codigo` INT NOT NULL,
  `descuento` DECIMAL(5,2) NOT NULL,
  `valido_hasta` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`transportistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`transportistas` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`estados_envio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`estados_envio` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`envios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`envios` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `venta_id` INT NOT NULL,
  `direccion_envio` TEXT NULL DEFAULT NULL,
  `estado_envio_id` INT NOT NULL,
  `transportista_id` INT NOT NULL,
  `fecha_envio` DATE NULL DEFAULT NULL,
  `fecha_entrega` DATE NULL DEFAULT NULL,
  `tracking` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`venta_id` ASC),
  INDEX (`estado_envio_id` ASC),
  INDEX (`transportista_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`venta_id`)
    REFERENCES `perfulandia`.`ventas` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`estado_envio_id`)
    REFERENCES `perfulandia`.`estados_envio` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`transportista_id`)
    REFERENCES `perfulandia`.`transportistas` (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`almacenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`almacenes` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `direccion` VARCHAR(255) NULL DEFAULT NULL,
  `ubicacion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`inventario` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `producto_id` BIGINT NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `almacen_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`producto_id` ASC),
  INDEX (`almacen_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`producto_id`)
    REFERENCES `perfulandia`.`productos` (`id`),
  CONSTRAINT ``
    FOREIGN KEY (`almacen_id`)
    REFERENCES `perfulandia`.`almacenes` (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`movimientos_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`movimientos_inventario` (
  `id` BIGINT NULL DEFAULT NULL AUTO_INCREMENT,
  `inventario_id` BIGINT NOT NULL,
  `cantidad` INT NULL DEFAULT NULL,
  `fecha` DATETIME NULL DEFAULT NULL,
  `motivo` VARCHAR(255) NULL DEFAULT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX (`inventario_id` ASC),
  CONSTRAINT ``
    FOREIGN KEY (`inventario_id`)
    REFERENCES `perfulandia`.`inventario` (`id`));

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`Tecnicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`Tecnicos` (
  `id` INT NOT NULL,
  `fechaIngreso` DATE NOT NULL,
  `Activo` TINYINT NOT NULL,
  `nombreCompleto` VARCHAR(45) NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `usuarios_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tecnicos_usuarios1_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_Tecnicos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `perfulandia`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`ticketSoporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`ticketSoporte` (
  `id` INT NULL DEFAULT NULL AUTO_INCREMENT,
  `asunto` VARCHAR(100) NULL DEFAULT NULL,
  `mensaje` TEXT NOT NULL,
  `estado` VARCHAR(50) NOT NULL,
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_resolucion` TIMESTAMP NULL,
  `clientes_id` BIGINT NOT NULL,
  `Tecnicos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticketSoporte_clientes1_idx` (`clientes_id` ASC),
  INDEX `fk_ticketSoporte_Tecnicos1_idx` (`Tecnicos_id` ASC),
  CONSTRAINT `fk_ticketSoporte_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `perfulandia`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticketSoporte_Tecnicos1`
    FOREIGN KEY (`Tecnicos_id`)
    REFERENCES `perfulandia`.`Tecnicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `perfulandia`.`CuponesAplicados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `perfulandia`.`CuponesAplicados` (
  `idCuponesAplicados` INT NOT NULL AUTO_INCREMENT,
  `DescuentoAplicado` TINYINT NOT NULL,
  `ventas_id` INT NOT NULL,
  `cupones_id` BIGINT NOT NULL,
  PRIMARY KEY (`idCuponesAplicados`),
  INDEX `fk_CuponesAplicados_ventas1_idx` (`ventas_id` ASC),
  INDEX `fk_CuponesAplicados_cupones1_idx` (`cupones_id` ASC),
  CONSTRAINT `fk_CuponesAplicados_ventas1`
    FOREIGN KEY (`ventas_id`)
    REFERENCES `perfulandia`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CuponesAplicados_cupones1`
    FOREIGN KEY (`cupones_id`)
    REFERENCES `perfulandia`.`cupones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
